new luci-app-koolproxy

diff --git a/files/etc/init.d/koolproxy b/files/etc/init.d/koolproxy
--- a/files/etc/init.d/koolproxy
+++ b/files/etc/init.d/koolproxy
@@ -12,7 +12,8 @@ USE_PROCD=1
 
 CONFIG=koolproxy
 PROG_PATH=/usr/share/koolproxy
-DATA_PATH=$PROG_PATH/data
+RULE_PATH=$PROG_PATH/data/rule
+TEMP_PATH=/tmp
 
 config_n_get() {
 	local ret=$(uci get $CONFIG.$1.$2 2>/dev/null)
@@ -43,7 +44,7 @@ load_exrule() {
 	config_get enable $1 load
 	if [ -n "$exrule" ]; then
 		if [ $enable -ne 1 ]; then
-			[ -n "$file" ] && [ -f $DATA_PATH/$file ] && rm -f $DATA_PATH/$file
+			[ -n "$file" ] && [ -f $RULE_PATH/$file ] && rm -f $RULE_PATH/$file
 			uci set koolproxy.$1.time=""
 			uci commit koolproxy
 			return
@@ -55,10 +56,16 @@ load_exrule() {
 			uci commit koolproxy
 		fi
 
-		if [ ! -f $DATA_PATH/$file ]; then
-			wget-ssl --quiet --timeout=5 --no-check-certificate $exrule -O $DATA_PATH/$file
-			uci set koolproxy.$1.time="`date +%Y-%m-%d" "%H:%M`"
-			uci commit koolproxy
+		if [ ! -f $RULE_PATH/$file ]; then
+			wget-ssl --quiet --timeout=5 --no-check-certificate $exrule -O $TEMP_PATH/$file
+			if [ "$?" == "0" ]; then
+				uci set koolproxy.$1.time="`date +%Y-%m-%d" "%H:%M`"
+				uci commit koolproxy
+				mv $TEMP_PATH/$file $RULE_PATH/$file
+			else
+				echo "koolproxy download rule $file failed!"
+				[ -f $TEMP_PATH/$file ] && rm -f $TEMP_PATH/$file
+			fi
 		fi
 	fi
 }
@@ -171,9 +178,13 @@ add_rule() {
 	iptables -t nat -N KOOLPROXY_HTTPS_ADB 2>/dev/null
 	#获取SHADOWSOCKS规则行号
 	SS_INDEX=`iptables -t nat -L PREROUTING|tail -n +3|sed -n -e '/^SHADOWSOCKS/='`
-	if [ -n "SS_INDEX" ]; then
+	if [ -n "$SS_INDEX" ]; then
 		let SS_INDEX+=1
+	else
+		SS_INDEX=`iptables -t nat -L PREROUTING|tail -n +3|sed -n -e '/^SS_SPEC*/='`
+		[ -n "$SS_INDEX" ] && let SS_INDEX+=1
 	fi
+
 	#确保添加到SHADOWSOCKS规则之后
 	iptables -t nat -I PREROUTING $SS_INDEX -p tcp -j KOOLPROXY
 	#创建所需的ipset
@@ -215,6 +226,7 @@ export_ipt_rules() {
 	FWI=$(uci get firewall.koolproxy.path 2>/dev/null)
 	[ -n "$FWI" ] || return 0
 	cat <<-CAT >>$FWI
+	iptables-save -c | grep -v "KOOLPROXY" | iptables-restore -c
 	iptables-restore -n <<-EOF
 	$(iptables-save | grep -E "KOOLPROXY|^\*|^COMMIT" |\
 		sed -e "s/^-A \(PREROUTING\)/-I \1 1/")
@@ -235,7 +247,7 @@ pre_start() {
 	iptables -t nat -C PREROUTING -p tcp -j KOOLPROXY 2>/dev/null && [ $? -eq 0 ] && return 0;
 	gen_ca
 	#加载RULES
-	config_foreach load_exrule rss_rule
+	#config_foreach load_exrule rss_rule
 	#/usr/share/koolproxy/koolproxy -d >/dev/null 2>&1 &
 	add_rule
 	add_koolproxy_cru
@@ -268,38 +280,30 @@ start_service() {
 	procd_set_param stderr 1
 	procd_close_instance
 
-	echo "koolproxy has started."
+	logger "koolproxy has started."
 }
 
 stop_service() {
 	post_stop
-	echo "koolproxy has stopped."
+	logger "koolproxy has stopped."
 }
 
 reload_service() {
-	echo "koolproxy reload service."
+	logger "koolproxy reload service."
 	stop
 	sleep 1
 	start
 }
 
 restart() {
-	echo "koolproxy restart service."
+	logger "koolproxy restart service."
 	stop
 	sleep 1
 	start
 }
 
-delay_start() {
-	(sleep $1 && start >/dev/null 2>&1) &
-}
-
 boot() {
 	local delay=$(config_t_get global startup_delay 0)
-	if [ "$delay" -gt 0 ]; then
-		delay_start $delay
-	else
-		start
-	fi
+	(sleep $delay && start >/dev/null 2>&1) &
 	return 0
 }
